# Generated by Django 5.0.1 on 2024-01-30 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_production_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='production',
            name='created_date',
        ),
    ]
