# Generated by Django 5.0.1 on 2024-01-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_alter_production_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='production',
            name='frequency',
        ),
    ]
