# Generated by Django 5.0.1 on 2024-02-01 03:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_alter_production_options_remove_production_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='production',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
