# Generated by Django 5.0.1 on 2024-02-21 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='location',
            name='created_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
