# Generated by Django 5.0.1 on 2024-02-21 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0009_alter_location_options_location_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qrcode',
        ),
    ]
